init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '1.2'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install broccoli broccoli-funnel rimraf tape

build: off

test_script:
  - ps: 'node test\test.js #PowerShell'
  - cmd: node test\test.js

cache:
  - node_modules
